language: python
python:
    - "3.6"

   
services:
    - docker


before_install:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin
    - ./ecr_credentials.sh

script:
    - eval $(aws ecr get-login --region us-east-1)
    - docker-compose build
    - docker tag foodapi:latest public.ecr.aws/d1d5z4z7/foodapi:latest   
    - docker push public.ecr.aws/d1d5z4z7/foodapi:latest

