language: python
python:
    - "3.6"

services:
- docker

before_deploy:
    - sudo apt update
    - sudo apt-get install awscli
    - sudo apt install python
    - apt install python-pip
    - sudo apt-get install docker.io
    - 'aws configure'
 

script:
    - eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - docker-compose build
    - docker tag foodapi:latest public.ecr.aws/g5w5n8y2/foodapi:latest
    - docker push public.ecr.aws/g5w5n8y2/foodapi:latest

