- name: Automate Docker with ansible
  hosts: localhost
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Adding Docker Repository
      yum_repository:
        name: Docker  
        description: Docker repo
        baseurl: https://download.docker.com/linux/ubuntu/dists/bionic/stable/
        gpgcheck: no
        enabled: yes
      register:  a_varible
    - debug:
        var: a_varible

   
    
    - name : Installing docker SDK
      command: "pip3 install docker"
      register: d_varible
    - debug:
        var: d_varible

    - name : pull image of https webserver
      docker_image:
        name: https
        source: pull
      register : e_varible
    - debug:
        var: e_varible

