version: "3.6"  # optional since v1.27.0
services:
     web:
       build:
         context: .
       volumes:
         - ./app
       ports:
         - "5000:5000"
       image: developer9408/foodapi