- name: ansible user
  hosts: localhost
  become: true
  become_method: sudo
  become_user: root

  tasks:
     - ec2:
         aws_access_key: AKIA5WV354T3LDA4HR6O
         aws_secret_key: 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
         key_name: aiapi new key
         group_id: sg-03c7eccdbf2c30b50
         instance_type: t2.micro
         wait: yes
         wait_timeout: 500
         image: "ami-0747bdcabd34c712a"
         count: 1
         instance_tags: 
           Name: prod-instance 
         monitoring: yes
         region: us-east-1   
         vpc_subnet_id: subnet-947a86d8
         assign_public_ip: yes
       
